= bespoke-multimedia
Dan Allen <https://github.com/mojavelinux>
// Settings:
:idprefix:
:idseparator: -
ifdef::env-github[:badges:]
// Variables:
:release-version: v1.0.3
// URIs:
:uri-raw-file-base: https://raw.githubusercontent.com/opendevise/bespoke-multimedia/{release-version}

ifdef::badges[]
image:https://img.shields.io/npm/v/bespoke-multimedia.svg[npm package, link=https://www.npmjs.com/package/bespoke-multimedia]
image:https://img.shields.io/travis/opendevise/bespoke-multimedia/master.svg[Build Status (Travis CI), link=https://travis-ci.org/opendevise/bespoke-multimedia]
endif::[]

Toggles playback of multimedia and restarts SVG and GIF animations on the active slide in a http://markdalgleish.com/projects/bespoke.js[Bespoke.js] presentation.

== Download

Download the {uri-raw-file-base}/dist/bespoke-multimedia.min.js[production mode version] or the {uri-raw-file-base}/dist/bespoke-multimedia.js[development mode version], or use a package manager.

=== npm

```bash
$ npm install bespoke-multimedia
```

=== Bower

```bash
$ bower install bespoke-multimedia
```

== Example

//http://opendevise.github.io/bespoke-multimedia[View the demo] online.

This repository includes a demo folder the shows this plugin in action.
To view it locally, you first need to clone this repository:

 $ git clone https://github.com/opendevise/bespoke-multimedia && cd bespoke-multimedia

Next, install the dependencies inside the project folder using npm:

 $ npm install

Finally, visit the file [path]_demo/index.html_ in your browser and navigate between slides to see the multimedia playback in action.

== Usage

This plugin is shipped in a https://github.com/umdjs/umd[UMD format], meaning that it is available as a CommonJS/AMD module or as a browser global.

For example, when using CommonJS modules:

```js
var bespoke = require('bespoke'),
  multimedia = require('bespoke-multimedia');

bespoke.from('.deck', [
  multimedia()
]);
```

When using browser globals:

```js
bespoke.from('.deck', [
  bespoke.plugins.multimedia()
]);
```

== License

http://en.wikipedia.org/wiki/MIT_License[MIT License]
